stages:
    - test
    - upload
tfsec:
  tags:
    - "docker"
  stage: test
  image:
    name: aquasec/tfsec
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    -  tfsec -f junit --out tfsec.test.xml
  artifacts:
    when: always
    reports:
      junit: tfsec.test.xml
  only:
    - merge_requests
tflint:
  tags:
    - "docker"
  stage: test
  image:
    name: ghcr.io/terraform-linters/tflint
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    -  tflint --init
    -  tflint . -f junit > tflint.test.xml
  artifacts:
    when: always
    reports:
      junit: tflint.test.xml
  only:
    - merge_requests
checkov:
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  tags:
    - "docker"
  stage: test
  script:
    - checkov -d . -o junitxml --output-file-path checkov-out
  artifacts:
    when: always
    reports:
      junit: checkov-out/**
  only:
    - merge_requests
upload:
  needs:
    - tfsec
    - tflint
    - checkov
  tags:
    - "docker"
  stage: upload
  # image: curlimages/curl:latest
  image: mrnonz/alpine-git-curl
  variables:
    TERRAFORM_MODULE_DIR: ${CI_PROJECT_DIR} # The path to your Terraform module
    TERRAFORM_MODULE_NAME: ${CI_PROJECT_NAME} # The name of your Terraform module
    TERRAFORM_MODULE_SYSTEM: local # The system or provider your Terraform module targets (ex. local, aws, google)
    # TERRAFORM_MODULE_VERSION: ${CI_COMMIT_TAG} # Tag commits with SemVer for the version of your Terraform module to be published
  script:
    - TERRAFORM_MODULE_VERSION=$(git describe --tags --abbrev=0)
    - TERRAFORM_MODULE_NAME=$(echo "${TERRAFORM_MODULE_NAME}" | tr " _" -) # module-name must not have spaces or underscores, so translate them to hyphens
    - tar -vczf ${TERRAFORM_MODULE_NAME}-${TERRAFORM_MODULE_SYSTEM}-${TERRAFORM_MODULE_VERSION}.tgz -C ${TERRAFORM_MODULE_DIR} --exclude=./.git .
    - ls -la
    - 'curl --fail-with-body --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}"
         --upload-file ${TERRAFORM_MODULE_NAME}-${TERRAFORM_MODULE_SYSTEM}-${TERRAFORM_MODULE_VERSION}.tgz
         ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/terraform/modules/${TERRAFORM_MODULE_NAME}/${TERRAFORM_MODULE_SYSTEM}/${TERRAFORM_MODULE_VERSION}/file'
  # rules:
  #   - if: $CI_COMMIT_TAG
  only:
    - merge_requests